### ISSUE TITLE
Error:  could not convert string to float

### ISSUE THREAD

**Issue by glermaidt** [viadee/docker-hub-rate-limit-exporter#15] opened 2021-03-30 16:38 UTC
Running tag 1.15.  Receving this in the container logs:

```
HTTP Headers START
Content-Length: 2782
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
Date: Tue, 30 Mar 2021 17:04:21 GMT
Strict-Transport-Security: max-age=31536000
RateLimit-Limit: ;w=21600
RateLimit-Remaining: ;w=21600
HTTP Headers END
Notice: Extracting limit from string: ;w=21600
Notice: Extracting limit from string: ;w=21600
Notice: Using Docker Hub credentials for 'idtdevops'
Notice: Response token:'{"token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK1RDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0U1RVbEdPbEZNUmpRNlEwZFFNenBSTWtWYU9sRklSRUk2VkVkRlZUcFZTRlZNT2taTVZqUTZSMGRXV2pwQk5WUkhPbFJMTkZNNlVVeElTVEFlRncweU1UQXhNalV5TXpFMU1EQmFGdzB5TWpBeE1qVXlNekUxTURCYU1FWXhSREJDQmdOVkJBTVRPMVZQU1ZJNlJFMUpWVHBZVlZKUk9rdFdRVXc2U2twTFZ6cExORkpGT2tWT1RFczZRMWRGVERwRVNrOUlPbEpYTjFjNlRrUktWRHBWV0U1WU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbnZBeVpFK09sZHgrY3hRS0RBWUtmTHJJYk5rK2hnaEg3Ti9mTFpMVDhEYXVPMXRoTWdoamxjcGhFVkNuYTFlMEZpOHVsUlZ4WG1HdWpZVDNXbnFsZ2ZpM2ZYTUQvQlBRTmlkWHZkeWprbDFZS3dPTkl3TkFWMnRXbExxaXFsdGhSWkFnTFdvWWZZMXZQMHFKTFZBbWt5bUkrOXRBcEMxNldNZ1ZFcHJGdE1rNnV0NDlMcDlUR1J0aDJQbHVWc3RSQ1hVUGp4bjI0d3NnYlUwVStjWTJSNEpyZmVJdzN0T1ZKbXNESkNaYW5SNmVheFYyVFZFUkxoZnNGVTlsSHAzcldCZ1RuNVRCSHlMRDNRdGVFLzJ3L3MvcUxZcmdIK1hCMmZBazJPd1NIRG5YWDg4WWVJd0EyVGJJMDdYNS8xQnVsaUwrUDduOWVBT1RmbDkxVlZwNER3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFZUMGxTT2tSTlNWVTZXRlZTVVRwTFZrRk1Pa3BLUzFjNlN6UlNSVHBGVGt4TE9rTlhSVXc2UkVwUFNEcFNWemRYT2s1RVNsUTZWVmhPV0RCR0JnTlZIU01FUHpBOWdEdFNUVWxHT2xGTVJqUTZRMGRRTXpwUk1rVmFPbEZJUkVJNlZFZEZWVHBWU0ZWTU9rWk1WalE2UjBkV1dqcEJOVlJIT2xSTE5GTTZVVXhJU1RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBkN3l1azQrWElabmtQb3RJVkdCeHBRSndpMzQwdExSb3R3Qzl4NkJpdWNDSUhFSmIyWGg0QzhtYVZic1Exd3ZUSCthRGV0VXhBS21lYkdXa3F6Z1J1Z1QiXX0.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6InJhdGVsaW1pdHByZXZpZXcvdGVzdCIsImFjdGlvbnMiOlsicHVsbCJdfV0sImF1ZCI6InJlZ2lzdHJ5LmRvY2tlci5pbyIsImV4cCI6MTYxNzEyNDE2OCwiaWF0IjoxNjE3MTIzODY4LCJpc3MiOiJhdXRoLmRvY2tlci5pbyIsImp0aSI6IjV5NDhEcVExWVRoLXpETkZ6Z2l2IiwibmJmIjoxNjE3MTIzNTY4LCJzdWIiOiI3MDEzZWVjZi1iMTMyLTQzNDAtYTc5Mi02ODM0ZWQzOWQ4YzAifQ.Wars9Mzhj1Kkmhv5EydfF8o6IrhStQHNgLs7McVnjNxZaJsm2w-rs1DZgUoav7FnBcd9pQPKC2aQJRtKmko3MyfIkdGa59o5_sU2Q3hPDxCtGFg9wzwCKHeBUDt6Ziq5ZuVbnwb-QnuVuCj36_9mdBf2up8pGGc1MqSnO2u6L8xZd2JboUHYQH29oCtoumBo9hKtejS0l5--kYe2z2CZ_Yi1IHf54TAUwvL6U59J2wzu-uAk2iV-s8C9XVH5t0s_INOEPvW7Ev5meQrjsdDd-K-4sKyqpFUei07-cntwUtF7-aYEeJ-_t1-vUtqKSWZ5bJVeVFMg77MHbzIp2TBi9g", "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDK1RDQ0FwK2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0U1RVbEdPbEZNUmpRNlEwZFFNenBSTWtWYU9sRklSRUk2VkVkRlZUcFZTRlZNT2taTVZqUTZSMGRXV2pwQk5WUkhPbFJMTkZNNlVVeElTVEFlRncweU1UQXhNalV5TXpFMU1EQmFGdzB5TWpBeE1qVXlNekUxTURCYU1FWXhSREJDQmdOVkJBTVRPMVZQU1ZJNlJFMUpWVHBZVlZKUk9rdFdRVXc2U2twTFZ6cExORkpGT2tWT1RFczZRMWRGVERwRVNrOUlPbEpYTjFjNlRrUktWRHBWV0U1WU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbnZBeVpFK09sZHgrY3hRS0RBWUtmTHJJYk5rK2hnaEg3Ti9mTFpMVDhEYXVPMXRoTWdoamxjcGhFVkNuYTFlMEZpOHVsUlZ4WG1HdWpZVDNXbnFsZ2ZpM2ZYTUQvQlBRTmlkWHZkeWprbDFZS3dPTkl3TkFWMnRXbExxaXFsdGhSWkFnTFdvWWZZMXZQMHFKTFZBbWt5bUkrOXRBcEMxNldNZ1ZFcHJGdE1rNnV0NDlMcDlUR1J0aDJQbHVWc3RSQ1hVUGp4bjI0d3NnYlUwVStjWTJSNEpyZmVJdzN0T1ZKbXNESkNaYW5SNmVheFYyVFZFUkxoZnNGVTlsSHAzcldCZ1RuNVRCSHlMRDNRdGVFLzJ3L3MvcUxZcmdIK1hCMmZBazJPd1NIRG5YWDg4WWVJd0EyVGJJMDdYNS8xQnVsaUwrUDduOWVBT1RmbDkxVlZwNER3SURBUUFCbzRHeU1JR3ZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQVBCZ05WSFNVRUNEQUdCZ1JWSFNVQU1FUUdBMVVkRGdROUJEdFZUMGxTT2tSTlNWVTZXRlZTVVRwTFZrRk1Pa3BLUzFjNlN6UlNSVHBGVGt4TE9rTlhSVXc2UkVwUFNEcFNWemRYT2s1RVNsUTZWVmhPV0RCR0JnTlZIU01FUHpBOWdEdFNUVWxHT2xGTVJqUTZRMGRRTXpwUk1rVmFPbEZJUkVJNlZFZEZWVHBWU0ZWTU9rWk1WalE2UjBkV1dqcEJOVlJIT2xSTE5GTTZVVXhJU1RBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQTBkN3l1azQrWElabmtQb3RJVkdCeHBRSndpMzQwdExSb3R3Qzl4NkJpdWNDSUhFSmIyWGg0QzhtYVZic1Exd3ZUSCthRGV0VXhBS21lYkdXa3F6Z1J1Z1QiXX0.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6InJhdGVsaW1pdHByZXZpZXcvdGVzdCIsImFjdGlvbnMiOlsicHVsbCJdfV0sImF1ZCI6InJlZ2lzdHJ5LmRvY2tlci5pbyIsImV4cCI6MTYxNzEyNDE2OCwiaWF0IjoxNjE3MTIzODY4LCJpc3MiOiJhdXRoLmRvY2tlci5pbyIsImp0aSI6IjV5NDhEcVExWVRoLXpETkZ6Z2l2IiwibmJmIjoxNjE3MTIzNTY4LCJzdWIiOiI3MDEzZWVjZi1iMTMyLTQzNDAtYTc5Mi02ODM0ZWQzOWQ4YzAifQ.Wars9Mzhj1Kkmhv5EydfF8o6IrhStQHNgLs7McVnjNxZaJsm2w-rs1DZgUoav7FnBcd9pQPKC2aQJRtKmko3MyfIkdGa59o5_sU2Q3hPDxCtGFg9wzwCKHeBUDt6Ziq5ZuVbnwb-QnuVuCj36_9mdBf2up8pGGc1MqSnO2u6L8xZd2JboUHYQH29oCtoumBo9hKtejS0l5--kYe2z2CZ_Yi1IHf54TAUwvL6U59J2wzu-uAk2iV-s8C9XVH5t0s_INOEPvW7Ev5meQrjsdDd-K-4sKyqpFUei07-cntwUtF7-aYEeJ-_t1-vUtqKSWZ5bJVeVFMg77MHbzIp2TBi9g", "expires_in": 300, "issued_at": "2021-03-30T17:04:28.84025098Z"}'
HTTP Headers START
Content-Length: 2782
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
Date: Tue, 30 Mar 2021 17:04:28 GMT
Strict-Transport-Security: max-age=31536000
RateLimit-Limit: ;w=21600
RateLimit-Remaining: ;w=21600
HTTP Headers END
Notice: Extracting limit from string: ;w=21600
Notice: Extracting limit from string: ;w=21600
Notice: Using Docker Hub credentials for 'idtdevops'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 53, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 41, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 138, in generate_latest
    output.append(sample_line(s))
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 104, in sample_line
    line.name, labelstr, floatToGoString(line.value), timestamp)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/utils.py", line 9, in floatToGoString
    d = float(d)
ValueError: ("could not convert string to float: ''", Metric(dockerhub_limit_remaining_requests_total, Docker Hub Rate Limit Remaining Requests, gauge, , [Sample(name='dockerhub_limit_remaining_requests_total', labels={'limit': 'remaining_requests_total'}, value='', timestamp=None, exemplar=None)]))
```

It seems there is no numeric value being retrieved using my authenticated user.

`Notice: Extracting limit from string: ;w=21600`
`Notice: Extracting limit from string: ;w=21600`

Let me know if you need further info.

**Comment by TJM** [comment] 2021-03-30 23:26
I am seeing the same thing with anonymous...
running chart version `0.2.6`, or container `viadee/docker-hub-rate-limit-exporter:version-1.5`

```
HTTP Headers START
Content-Length: 2782
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
Date: Tue, 30 Mar 2021 23:17:12 GMT
Strict-Transport-Security: max-age=31536000
RateLimit-Limit: ;w=21600
RateLimit-Remaining: ;w=21600
HTTP Headers END
Notice: Extracting limit from string: ;w=21600
Notice: Extracting limit from string: ;w=21600
Notice: Using anonymous Docker Hub token
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 53, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 41, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 138, in generate_latest
    output.append(sample_line(s))
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 104, in sample_line
    line.name, labelstr, floatToGoString(line.value), timestamp)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/utils.py", line 9, in floatToGoString
    d = float(d)
ValueError: ("could not convert string to float: ''", Metric(dockerhub_limit_remaining_requests_total, Docker Hub Rate Limit Remaining Requests, gauge, , [Sample(name='dockerhub_limit_remaining_requests_total', labels={'limit': 'remaining_requests_total'}, value='', timestamp=None, exemplar=None)]))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 53, in prometheus_app
    status, header, output = _bake_output(registry, accept_header, params)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 41, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 138, in generate_latest
    output.append(sample_line(s))
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 104, in sample_line
    line.name, labelstr, floatToGoString(line.value), timestamp)
  File "/usr/local/lib/python3.9/site-packages/prometheus_client/utils.py", line 9, in floatToGoString
    d = float(d)
ValueError: ("could not convert string to float: ''", Metric(dockerhub_limit_remaining_requests_total, Docker Hub Rate Limit Remaining Requests, gauge, , [Sample(name='dockerhub_limit_remaining_requests_total', labels={'limit': 'remaining_requests_total'}, value='', timestamp=None, exemplar=None)]))
```


The headers do not contain a rate limit... did they turn that off?

```
[tmcneely@local admin-tools] $ TOKEN=$(curl -Ss "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token)
[tmcneely@local admin-tools] $ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
HTTP/1.1 200 OK
Content-Length: 2782
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
Date: Tue, 30 Mar 2021 23:30:06 GMT
Strict-Transport-Security: max-age=31536000
RateLimit-Limit: ;w=21600
RateLimit-Remaining: ;w=21600
```

**Comment by prostohant** [comment] 2021-03-31 08:26
Looks like it works time to time
`test@test ~ $ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1 | grep RateLimi`
`RateLimit-Limit: ;w=21600`
`RateLimit-Limit: ;w=21600`
`test@test ~ $ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1 | grep RateLimit`
`RateLimit-Limit: ;w=21600`
`RateLimit-Remaining: ;w=21600`
`test@test ~ $ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1 | grep RateLimit`
`RateLimit-Limit: 100;w=21600`
`RateLimit-Remaining: 100;w=21600`
`test@test ~ $ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1 | grep RateLimit`
`RateLimit-Limit: ;w=21600`
`RateLimit-Remaining: ;w=21600`

**Comment by mstein11** [comment] 2021-04-23 13:12
Sorry for the late reply, I have been quite busy recently.

It seems the error has disappeared? Can somebody confirm that it's working again for them?

**Comment by mstein11** [comment] 2021-04-23 13:28
Wait, it seems the behavior described here is the same as in #6, right?  I think what happened here is that docker hub had an issue with their api, which resulted in the problem described in #6 to occur permanently for some time?

Can somebody confirm this guess?

**Comment by immanuelfodor** [comment] 2021-04-23 14:27
Yes, the API seems to be fixed now, it's always returning results. For details, see this comment: https://github.com/viadee/docker-hub-rate-limit-exporter/issues/6#issuecomment-825680538

**Comment by mstein11** [comment] 2021-04-23 14:37
Duplicate of #6

**Closed as completed by mstein11** 2021-04-23 14:37 UTC
